config/routes.rb
Rails.application.routes.draw do

  root 'subs#index'

  resources :subs do 
    resources :topics
  end

  scope '/topics/:topic_id', as: 'topic' do
    resources :comments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_topic
  
  def new
    @comment = Comment.new
  end

  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.save
      redirect_to sub_topic_path(@topic.sub_id, @topic)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :author)
  end

  def find_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :find_sub, only: [:show, :edit, :update, :destroy]
  after_action :more_cowbell


  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @sub = Sub.new
    render partial: "form"
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to @sub
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @sub.update(sub_params)
      redirect_to @sub
    else
      render :edit
    end
  end

  def destroy
    @sub.destroy
    redirect_to subs_path
  end

  private

  def find_sub
    @sub = Sub.find(params[:id])
  end

  def more_cowbell
    Rails.logger.info "DING DING DING DING"
  end

  def sub_params
    params.require(:sub).permit(:name)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_sub
  before_action :find_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = @sub.topics
  end

  def show
  end

  def new
    @topic = @sub.topics.new
    render partial: "form"
  end

  def create
    @topic = @sub.topics.new(topic_params)
    if @topic.save
      redirect_to [@sub, @topic]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end

  def destroy
    @topic.delete
    redirect_to sub_topics_path
  end

  private

  def find_sub
    @sub = Sub.find(params[:sub_id])
  end

  def find_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><%= comment.body %></p>
<hr />

app/views/comments/new.html.erb
<h1> Create Comment</h1>
<hr />
<%= form_for [@topic, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>

<hr />
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Click a Sub To View Content</h1>
<%= link_to 'Create a new sub', new_sub_path %>
<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.name, sub %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br />
<%= link_to 'Delete Sub', @sub, method: :delete %>
<br />
<%= link_to 'Back to Subs', subs_path %>

app/views/topics/_form.html.erb
<h1><%= @topic.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Click a Topic To View Content</h1>
<%= link_to 'Create a new topic', new_sub_topic_path(@sub) %>
- | -
<%= link_to 'Back to Sub', sub_path(@sub) %>
<hr />
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, [@sub, topic] %></li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @sub.name %> - <%= @topic.name %></h1>
<p><%= @topic.body %></p>

<h3> Comments </h3>
<% @topic.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>

<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
- | -
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
- | -
<%= link_to 'Back To Topics', sub_topics_path(@sub) %>
- | -
<%= link_to 'Write Comment', new_topic_comment_path(@topic) %>